#ifndef CONST_H_INCLUDED
#define CONST_H_INCLUDED
    #define SIZE_BLOCK 34
    #define NB_SQUARES_WIDTH    12
    #define NB_SQUARES_LENGTH   12
    #define WIDTH_WINDOW     NB_SQUARES_WIDTH * SIZE_BLOCK
    #define LENGTH_WINDOW     NB_SQUARES_LENGTH * SIZE_BLOCK

    enum {UP, DOWN, LEFT, RIGHT};
    enum {EMPTY, WALL, BALL, NAMEK_GREEN, SONGUKU, NAMEK_RED};


#endif // CONST_H_INCLUDED
